{% set name = "pylibacl" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9d9ffb580e0c582d5de598087f75f6940458b23810c615529143c61b172bf922

build:
  skip: true  # [not linux]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
    - libacl
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - posix1e
  commands:
    - pytest tests
    - pip check
  requires:
    - pip
    - pytest

about:
  home: https://pylibacl.k1024.org/
  summary: POSIX.1e ACLs for python
  description: >
    This is a C extension module for Python which implements POSIX ACLs manipulation. It is a wrapper on top of the systems's acl C library - see acl(5).
  license: LGPL-2.1-or-later
  license_file: COPYING
  doc_url: https://pylibacl.k1024.org/
  dev_url: https://github.com/iustin/pylibacl

extra:
  recipe-maintainers:
    - tjtg
